import "./globals.css";
import { Space_Grotesk } from "next/font/google";

const space = Space_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Bangla Font CDN - World's Largest Free Bangla Font CDN Library",
  description: "Generated by create next app",
  icons: {
    icon: "/svg/favicon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans">{children}</body>
    </html>
  );
}
